# Generated by Django 3.2 on 2024-01-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AstralAssetsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='investment_plan_name',
            field=models.CharField(blank=True, default='Not Found', max_length=20, null=True),
        ),
    ]
