# Generated by Django 3.2 on 2024-01-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AstralAssetsApp', '0002_alter_client_investment_plan_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='wallet_address',
        ),
        migrations.AddField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
