# Generated by Django 3.2 on 2024-01-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AstralAssetsApp', '0003_auto_20240118_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default='update your account', max_length=64, null=True),
        ),
    ]
