# Generated by Django 3.2 on 2024-01-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AstralAssetsApp', '0004_auto_20240118_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc', models.CharField(blank=True, max_length=68, null=True)),
                ('usdttrc20', models.CharField(blank=True, max_length=68, null=True)),
                ('ltc', models.CharField(blank=True, max_length=68, null=True)),
                ('doge', models.CharField(blank=True, max_length=68, null=True)),
                ('eth', models.CharField(blank=True, max_length=68, null=True)),
                ('trx', models.CharField(blank=True, max_length=68, null=True)),
            ],
        ),
    ]
