# Generated by Django 3.2 on 2024-10-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AstralAssetsApp', '0005_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='usdc',
            field=models.CharField(blank=True, max_length=68, null=True),
        ),
    ]
