# Generated by Django 3.2 on 2024-11-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AstralAssetsApp', '0006_wallet_usdc'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='xrp',
            field=models.CharField(blank=True, max_length=68, null=True),
        ),
    ]
